version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: mobileapp
    user: root
    ports:
      - "8081:8080"
      - "50001:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped

  reactnative:
    build: .
    container_name: reactnative_app
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app
    command: >
      bat -c "npm install && npx expo start --tunnel"
    depends_on:
      - jenkins